### ISSUE TITLE
UML-Klassendiagramm für Ausrüstung

### ISSUE THREAD

**Issue by SchmidtWla** [andreasmauel/HenPaSa_AnWla#2]
• Rüstung
• Waffen
• Magische Gegenstände
• Tränke
• Teile des gesuchten Artifakts für das Spieziel

Template-Method

**Comment by freaksheep1** [comment]
Unser erster Entwurf: 



![Image](https://user-images.githubusercontent.com/56644172/227473711-25c2affe-9b23-428f-b4b9-4d700bf704cc.png)
