### ISSUE TITLE
UML-Klassendiagram Spielplan Erstellung

### ISSUE THREAD

**Issue by SchmidtWla** [andreasmauel/HenPaSa_AnWla#33]
Erstellen eines ersten Entwurfs für ein Klassendiagramm für das Spielfeld.

**Comment by freaksheep1** [comment]
Unser Entwurf:

![Image](https://user-images.githubusercontent.com/56644172/228747396-36d7060e-0c54-426c-97ed-f5ee067e2f4d.png)
