### ISSUE TITLE
UML-Klassendiagramm für Charaktere

### ISSUE THREAD

**Issue by andreasmauel** [andreasmauel/HenPaSa_AnWla#4]
Es muss ein Klassendiagramm für die Spielcharaktere und die Monster implementiert werden.

**Comment by freaksheep1** [comment]
Unser erster Entwurf: 



![Image](https://user-images.githubusercontent.com/56644172/227485175-536f75b0-97d9-435e-8e88-bcaa4b0a0ad5.png)
