### ISSUE TITLE
UML-Klassendiagramm Spielcontroller

### ISSUE THREAD

**Issue by andreasmauel** [andreasmauel/HenPaSa_AnWla#40]
Ein erster Entwurf für den Spielcontroller als UML-Diagramm soll erstellt werden.

**Comment by freaksheep1** [comment]
Unser erster Entwurf:

![Image](https://user-images.githubusercontent.com/56644172/228748003-ce9747f1-a5b5-4699-8c8a-bb1105b3543f.png)
