### ISSUE TITLE
Statusbildschirm implementieren

### ISSUE THREAD

**Issue by NekoLen** [andreasmauel/HenPaSa_AnWla#54]
Der Statusbildschirm für den Player inklusive Waffen / Artefakt / Spell Auswahl soll erstellt werden: 

Unser erster Entwurf:

![Image](https://user-images.githubusercontent.com/56644172/228758782-c553fed5-579d-4929-b821-884f0b367167.jpg)

**Comment by freaksheep1** [comment]
Das Endergebnis:



![Image](https://user-images.githubusercontent.com/56644172/228763195-44045b2b-ccc4-49da-84b6-c4177090551b.PNG)
