### ISSUE TITLE
GUI Framework/Tool recherchieren

### ISSUE THREAD

**Issue by andreasmauel** [andreasmauel/HenPaSa_AnWla#8]
Recherchieren von verschiedenen GUI Tools, herausarbeiten von Vor- und Nachteilen um abzuwägen welches für uns infrage kommt.

**Comment by freaksheep1** [comment]
Haben uns am Ende für Java Swing entschieden, da wir dieses bereits kennengelernt haben und Erfahrungen sammeln konnten und die Einarbeitungszeit deswegen wegfällt.
