### ISSUE TITLE
UML-Klassendiagramm für Spielcontroller

### ISSUE THREAD

**Issue by andreasmauel** [andreasmauel/HenPaSa_AnWla#9]
Die Grundlagen für den Spielcontroller sollen in einem UML-Diagramm festgehalten werden. Grundlegend soll es einen Spielcontroller geben, der in mehrere Untercontroller aufgeteilt wird. Der Spielcontroller ist für den reibungslosen Ablauf des Spiels so wie die Einhaltung der Spielregeln verantwortlich.  Die Untercontroller kontrollieren nochmal einzelne Bereiche des Spiels wie z. B. den Kampf, den Ablauf einer Spielrunde, aktive Effekte usw.

**Comment by freaksheep1** [comment]
Der erste Entwurf unseres Spielcontrollers.

![Image](https://user-images.githubusercontent.com/56644172/227477569-9ebfb746-988f-4448-8f91-4a261fec862f.png)
